# Site
title: Home
subtitle: ''
description: ''
keywords:
author: ''
language: en
timezone: ''


# Setup
title:               Lanyon
tagline:             'A Jekyll theme'
description:         ''
url:                 http://alxendweb.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              
  url:               
  email:             

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
