# 站点设置
title: Sai Wang
#description: 
url: "https://alxendweb.github.io"
repository: "你的用户名/你的仓库名"

# 构建设置
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# 导航栏菜单
header_pages:
  - index.md
  - about.md

# 作者信息
#author:
 # name: Sai Wang
 # email: wangs8@sustech.edu.cn
  #twitter: 你的Twitter账号

# 社交媒体链接
#twitter_username: 你的Twitter账号
#github_username: 你的GitHub账号
#linkedin_username: 你的LinkedIn账号

# 分页设置 (可选)
paginate: 5
paginate_path: "/blog/page:num/"

# 自定义头部和底部 (可选)
header_pages:
  - index.md
  - about.md
footer_pages:
  - privacy.md

# Google Analytics (可选)
google_analytics: UA-你的跟踪码
