
# Setup
title:               'Sai Wang'
tagline:             'Academic'
description:         ' '
url:                 alxendweb.github.io
paginate:            1
permalink:           pretty

#index.html

# Gems
plugins:
  - jekyll-paginate
