
# Setup
title:               'Sai Wang'
tagline:             'Neo'
description:         ' '
url:                 saiwang-neo.github.io
paginate:            1
permalink:           pretty

markdown: kramdown
kramdown:
  math_engine: mathjax
  mathjax:
    enable: true
    version: 3.2.0
    tex_extensions: [TeX]
    tex_inlineMath: [['$', '$']]
    tex_displayMath: [['$$', '$$']]


  

#index.html

# Gems
plugins:
  - jekyll-paginate

