
# Setup
title:               'Sai Wang'
tagline:             'Academic Website'
description:         ' '
url:                 http://alxendweb.github.io
paginate:            4
#permalink:           pretty

#index.html
