
# Setup
title:               'Sai Wang'
tagline:             'Neo'
description:         ' '
url:                 saiwang-neo.github.io
paginate:            1
permalink:           pretty

kramdown:
  math_engine: mathjax


#index.html

# Gems
plugins:
  - jekyll-paginate

