
# Setup
title:               'Sai Wang'
tagline:             'Academic Website'
description:         'tangle'
url:                 http://alxendweb.github.io
paginate:            4
#permalink:           pretty


