# 站点设置
title: Homepage
#description: 
url: "https://alxendweb.github.io"
repository: "你的用户名/你的仓库名"

# 构建设置
markdown: kramdown
theme: minima
plugins:
  - jekyll-fee




# Google Analytics (可选)
google_analytics: UA-你的跟踪码
