
# Setup
title:               'Sai Wang'
tagline:             'Academic Website'
description:         ' '
url:                 alxendweb.github.io
paginate:            4
#permalink:           pretty

#index.html
# Gems
plugins:
  - jekyll-paginate
