
# Setup
title:               'Sai Wang'
tagline:             'Neo'
description:         ' '
url:                 saiwang-neo.github.io
paginate:            1
permalink:           pretty

markdown: kramdown
kramdown:
  math_engine: mathjax

#index.html

# Gems
plugins:
  - jekyll-paginate

