
# Setup
title:               'Sai Wang'
tagline:             'Neo'
description:         ' '
url:                 saiwang-neo.github.io
paginate:            1
permalink:           pretty

kramdown:
  math_engine: mathjax

[markup.goldmark.renderer]
  unsafe = true
  [markup.goldmark.renderer.latex]
    enabled = true

#index.html

# Gems
plugins:
  - jekyll-paginate

